public class Main {
    public static void main(String[] args) {
        Solution no1 = new Solution();
        String sentence1 = "HaEaLaLaObWORLDb";
        String sentence2 = "SpIpGpOpNpGJqOqA";
        String sentence3 = "AxAxAxAoBoBoB";

        String input = "aHELLOa";
        input = "aHbEbLbLbOa";
        String res = no1.solution(input);
        System.out.println(res);
        input = "Ab";
        res = no1.solution(input);
        System.out.println(res);
        input = "H";
        res = no1.solution(input);
        System.out.println(res);
        input = "Ha";
        res = no1.solution(input);
        System.out.println(res);
        input = "HaEaLaLaO";
        res = no1.solution(input);
        System.out.println(res);
        input = "HaEaLaLaObWORLDb";
        res = no1.solution(input);
        System.out.println(res);
        input = "SpIpGpOpNpGJqOqA";
        res = no1.solution(input);
        System.out.println(res);
        input = "AxAxAxAoBoBoB";
        res = no1.solution(input);
        System.out.println(res);
        input = "oBoBo";
        res = no1.solution(input);
        System.out.println(res);
        input = "aTAEaHbObObN";//
        res = no1.solution(input);
        System.out.println(res + "*");
        input = "AabAPPLEb";
        res = no1.solution(input);
        System.out.println(res);
        input = "aTbAbEbHbObObNa";//
        res = no1.solution(input);
        System.out.println(res + "**");
        input = "aTbAbEHbObOcNa";
        res = no1.solution(input);
        System.out.println(res);
        input = "cA";
        res = no1.solution(input);
        System.out.println(res);
        input = "AaBbAbNbAbNbAa";
        res = no1.solution(input );
        System.out.println(res);
        input = "AaBbAbNbAbNbAaTRIPcHOOOc";
        res = no1.solution(input);
        System.out.println(res);
        input = "AaBbAbNbAbNbAaTRIPcdHOOOd";
        res = no1.solution(input);
        System.out.println(res);
        input = "AaBbAbNbAbNbAaTRIPHcOcOcO";
        res = no1.solution(input);
        System.out.println(res);
        input = "AaBbAbNbAbNbAadTeReIePdHcOcO";
        res = no1.solution(input);
        System.out.println(res );
        input = "AaBbAbNbAbNbAaTeReIePHcOcO";
        res = no1.solution(input);
        System.out.println(res);
        input = "TRIP";
        res = no1.solution(input);
        System.out.println(res);
        input = "aIaAM";
        res = no1.solution(input);
        System.out.println(res);
        input = "bAaOb";
        res = no1.solution(input);
        System.out.println(res + "*****");
        input = "HaEaLaLaOWaOaRaLaD";
        res = no1.solution(input);
        System.out.println(res + "_");
        input = "HaEaLaLObWORLDb";
        res = no1.solution(input);
        System.out.println(res);
        input = "abHELLObaWORLD";
        res = no1.solution(input);
        System.out.println(res + "__");
        input = "SpIpGpOpNpGJqOqAB";
        res = no1.solution(input);
        System.out.println(res);
        input = "SpIpGpOpNpGJqOqAkB";
        res = no1.solution(input);
        System.out.println(res);
        input = "SpIpGpOpNpGJqOqAkBr";
        res = no1.solution(input);
        System.out.println(res);
        input = "AaA";
        res = no1.solution(input);
        System.out.println(res);
        input = "aA";
        res = no1.solution(input);
        System.out.println(res);
        input = "aAaAaAaAa";
        res = no1.solution(input);
        System.out.println(res);
        input = "AaAaAaAaA";
        res = no1.solution(input);
        System.out.println(res);
        input = "aacc";
        res = no1.solution(input);
        System.out.println(res);
        input = "aAa";
        res = no1.solution(input);
        System.out.println(res);

        String res1 = no1.solution(sentence1);
        System.out.println(res1);
        String res2 = no1.solution(sentence2);
        System.out.println(res2);
        String res3 = no1.solution(sentence3);
        System.out.println(res3);
    }
}
